### ISSUE TITLE
Web user (apache) has no rights to create files in linked web folder

### ISSUE THREAD

**Issue by esseremmerik** [clickontyler/VirtualHostX-Issues#12]
It seems like the vagrant box has provided access to the folders with the vagrant user itself. From the SSH terminal I can create files in the linked folders, but the web application (apache) cannot create files and is using the "fallback" /tmp folder in the vagrant box. Any way to easily give the write access to the web user?

**Comment by tylerhall** [comment]
I believe you can issue a `chmod 755 dir-name` on the Mac host side to enable writing from within the vm.

**Comment by esseremmerik** [comment]
@tylerhall I don't know specifically our difference in setup, but the chmod 755 didn't help me in this case. I am able to write to this folder from the "old" VirtualHost 6 apache2 osx configuration but not from your vagrant box as apache user (I can write as the vagrant user from the shell). We also use homestead as vagrant box and this image has no issues writing to that shared folder so perhaps you can look into the folder / apache2 permissions again.

**Comment by tylerhall** [comment]
Hmm.

@esseremmerik In your homestead vm, what's the permissions and owner settings?

**Comment by gorelog** [comment]
Experiencing the same thing. Permissions were already 755.

**Comment by tylerhall** [comment]
This is (should be) fixed in version 7.1.6.

After updating the app, click "Apply Changes" again to set the new permissions and restart the virtual machine.

@gorelog @esseremmerik

**Comment by esseremmerik** [comment]
@tylerhall perfect solution, this works since 7.1.6 without problems.

**Comment by tylerhall** [comment]
Awesome. Thanks for letting me know.
