### ISSUE TITLE
Custom Directives in the GUI do not work

### ISSUE THREAD

**Issue by raguay** [clickontyler/VirtualHostX-Issues#16]
Hi,

The "Custom Directives" in the GUI for each host doesn't do anything. I had to edit them by hand in Vagrant. It would be nicer to just edit them here.

**Comment by tylerhall** [comment]
@raguay Can you provide any more details as to how they're not working? When I input text into the custom directives field and click "Apply Changes", I can see that text added to the virtual host's .conf file correctly.

Is that not what you're seeing?

**Comment by raguay** [comment]
No. I add text in the VHX7 gui and "Apply Changes". The conf files are not changed at all. I have to ssh into the Vagrant box and manually change them. My box doesn't seem to be mapping the conf directory to the virtual machine, but I'm not completely sure how to check. Is there a command to have vagrant tell all the redirects in a box?

**Comment by raguay** [comment]
BTW: Half the time I use "Apply Changes", the whole program just crashes. I have to manually shutdown the machine and then relaunch VHX7.

**Comment by tylerhall** [comment]
The crash will be fixed in the next release.
