### ISSUE TITLE
VBoxManage could not be found

### ISSUE THREAD

**Issue by tylerhall** [clickontyler/VirtualHostX-Issues#18]
When attempting to “Download and setup web server”, I get the following message:

The "VBoxManage" command or one of its dependencies could not
be found. Please verify VirtualBox is properly installed. You can verify
everything is okay by running "VBoxManage --version" and verifying
that the VirtualBox version is outputted.

If you're on Windows and just installed VirtualBox, you have to
log out and log back in for the new environmental variables to take
effect. If you're on Linux or Mac, verify your PATH contains the folder
that has VBoxManage in it.

**Comment by tylerhall** [comment]
https://clickontyler.com/support/a/65/vhx7-vboxmanage-not-found/

Further...

https://github.com/Parallels/vagrant-parallels/issues/248#issuecomment-176452730

**Comment by Karan02** [comment]
> https://clickontyler.com/support/a/65/vhx7-vboxmanage-not-found/

site is not working

**Comment by tylerhall** [comment]
Thank you. The correct link is...

https://help.clickontyler.com/en/article/65/vboxmanage-could-not-be-found
