### ISSUE TITLE
Can't start VM - machine is locked

### ISSUE THREAD

**Issue by tylerhall** [clickontyler/VirtualHostX-Issues#2]
Some users are reporting that the vm is locked and can't be started.

![1fecaa60-20db-11e6-9510-9b39ff11cc1b](https://cloud.githubusercontent.com/assets/57670/15486092/c1086010-2108-11e6-9915-f86f10628f11.png)

**Comment by raguay** [comment]
Is there a fix for this yet? Where are the lock files kept? Couldn't we just go in and delete them?

**Comment by tylerhall** [comment]
I don't know where the lock files are kept.

**Comment by raguay** [comment]
Oh. I guess that is why I'm having such a hard time finding them.

**Comment by raguay** [comment]
Well, I did a destroy machine to start over, but it is now stuck on the Welcome screen. I'm getting my other Vagrant machines to work, but I can't seem to get that machine to work. Where is the Vagrant file for that machine?

**Comment by tylerhall** [comment]
```
~/Library/Application Support/com.clickontyler.virtualhostx/VirtualHostX/Vagrantfile
```

**Comment by raguay** [comment]
Okay. I fixed my system by shutting down VHX7, removing ~/Library/Application Support/com.clickontyler.virtualhostx/VirtualHostX/.vagrant directory and the ~/.vagrant.d directory entirely, restart VHX7 and it will recreate the virtual machine from scratch, once it had the system running in vagrant again, I restarted by using the Apply button in VHX7, and now my system is working as much as it did before the crash.

**Comment by tylerhall** [comment]
So it's good now?

**Comment by raguay** [comment]
Yep. I am able to use it and I have two projects on it. I've never updated a
vagrant box. Does the had tweaking persist or will I have to redo it? When
will the Directory Directives in the GUI work? I had to add them by hand in
the virtual machine.

**Comment by tylerhall** [comment]
If you make your changes to the Vagrantfile, they'll persist.

```
~/Library/Application Support/com.clickontyler.virtualhostx/VirtualHostX/Vagrantfile
```

**Comment by wpickup-zz** [comment]
I have the same problem.
In my case it can be fixed by reloading the VM.
At a command line, the steps are...

```
vagrant global-status
```

to get the machine-id.

```
vagrant reload machine-id
```

**Comment by tylerhall** [comment]
A StackOverflow answer also recommends issuing a reload command...

http://stackoverflow.com/questions/36667648/vagrant-cant-use-the-requested-machine-because-it-is-locked

That said, you should be able to use the "Reload" command under the "Virtual Machine" menu to fix this.
