### ISSUE TITLE
Can't power-on VHX7

### ISSUE THREAD

**Issue by davistech** [clickontyler/VirtualHostX-Issues#22]
I installed VHX7 and everything was working. Then I closed the app and re-opened it. Now I get this message when trying to power-on.

> Vagrant can't use the requested machine because it is locked! This
> means that another Vagrant process is currently reading or modifying
> the machine. Please wait for that Vagrant process to end and try
> again. Details about the machine are shown below:
> 
> Name: default
> Provider: virtualbox

System info:
Model Name:  Mac mini
Model Type:  Mid 2011
Model Identifier:  Macmini5,2
Processor Speed:  2.7 GHz
Memory Size:  8 GB 1333 MHz DDR3
Current Boot Operating System:  OS X 10.11.5 Build 15F34 (El Capitan)
Vagrant: ver 1.8.1
VirtualHostX: ver 7.1.2 (licensed)

**Comment by gorelog** [comment]
I get this too. Reload works for me to get the box back up and running. However, none of the sites worked. This morning after turning my machine on I still had to use the Reload options, but this time my sites came up.
