### ISSUE TITLE
Error: (null) - Upping

### ISSUE THREAD

**Issue by theDustRoom** [clickontyler/VirtualHostX-Issues#24]
Downloaded 7.1.2 in the hope it would resolve the issue I had with VMWare being installed but now I get:

`/bin/bash: -c: line 0: syntax error near unexpected token '('`
`/bin/bash: -c: line 0: '/usr/local/bin/vagrant up --provider virtualbox (null)'`

On launch and still get the VMWare error when trying to use **Step 3** of the setup process:

> An unexpected error occurred while loading the Vagrant VMware
> provider. Please contact support with the following
> error code: '7'.
> Vagrant failed to initialize at a very early stage:
> 
> The plugins failed to load properly. The error message given is
> shown below.
> 
> exit

**Comment by theDustRoom** [comment]
Still present in 7.1.4

**Comment by tylerhall** [comment]
I haven't been able to reproduce this. Worse, it's beyond my fixing since it appears to be a Vagrant issue.
