### ISSUE TITLE
Reload Apache config instead of restarting VM

### ISSUE THREAD

**Issue by davidpv** [clickontyler/VirtualHostX-Issues#26]
it could be an improvement reload or even restart apache instead of restarting the whole VM machine every time a change is made in vhosts in the VHX7 app.

**Comment by tylerhall** [comment]
I tried that, but unfortunately it's not enough. I also have to restart the VM in order to pickup the new synced web folders the user may had added/removed. As far as I know, there's no way to do that without restarting the vm.

**Comment by tylerhall** [comment]
If anyone knows how to add/remove synced Vagrant folders without reboot the machine, let me know and I'll re-open this issue.
