### ISSUE TITLE
Unable to download from server

### ISSUE THREAD

**Issue by uhlhosting** [clickontyler/VirtualHostX-Issues#31]
Hi I have the following error on VHX 7:

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/trusty64'
    default: URL: https://atlas.hashicorp.com/ubuntu/trusty64
==> default: Adding box 'ubuntu/trusty64' (v20160602.0.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20160602.0.0/providers/virtualbox.box
==> default: Box download is resuming from prior download progress

[K    default: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)
[KAn error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 416

**Comment by tylerhall** [comment]
Sounds like a temporary error with Vagrant's Atlas service (where the boxes are downloaded from). It's out of my control. I'd suggest trying again in a little while.

**Comment by uhlhosting** [comment]
the server works just fine...
