### ISSUE TITLE
Fix crash in - [NSAlert didEndAlert:returnCode:contextInfo:]

### ISSUE THREAD

**Issue by tylerhall** [clickontyler/VirtualHostX-Issues#46]
### Reason

No reason found. Full stack trace includes libobjc.A.dylib, AppKit, libsystem_pthread.dylib, Foundation.
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/24635/crash_reasons/134496658](https://rink.hockeyapp.net/manage/apps/24635/crash_reasons/134496658)

**Comment by flyweights** [comment]
How to solve the problem?I also met.
