### ISSUE TITLE
HTTP URL link error with VirtualHostX 7.2.0

### ISSUE THREAD

**Issue by tylerhall** [clickontyler/VirtualHostX-Issues#47]
Hi Tyler,

The "HTTPS" button in VirtualHostX v7.2.0 points to https://host:8433 instead of https://host:8443. Took me a few minutes to figure out why SSL wasn't working, realized it was just a typo'd port in the interface.

Best regards

**Comment by tylerhall** [comment]
Thanks! I'll get this fixed.

**Comment by mattsims** [comment]
I just ran into this too – still broken!  Glad you posted this issue else I would never have worked it out ;)

**Comment by tylerhall** [comment]
Fixed in 7.3.1. Released 1/26/2018.
