### ISSUE TITLE
==> default: VM not created. Moving on...

### ISSUE THREAD

**Issue by souhaiebtar** [clickontyler/VirtualHostX-Issues#51]
my connection was interrupted when i was installing virtualhostx vm ( when virtualhostx was downloading ubuntu trusty image), but virtualhostx tell me that the vm was correctly installed, Virtual Machine -> destroy won't work,  i uninstalled virtualhostx using appcleaner and cleanmymac, and installed it again, nothing change, ater destroying the virtual machine the welcome to virtualhostx screen appear again, and when i tape on step3. Download and setup the web server, nothing happen, and download doesn't start, the same UI keep showing, if i close it and open it again, the UI interface appear saying in down left corner virtual machine running( which is not the case), there is no VM in virtualbox, when i go to virtualmachine menu, power on power off pause resume reload, all show this message "default: VM not created. Moving on...", is there other file that i need to remove after uninstall, to be able to make a clean install again , please any help

**Comment by JSPlike** [comment]
가상머신 화면에 제대로 등록이 안된 것 같네요
