### ISSUE TITLE
no vhx.host domains entries in /etc/hosts

### ISSUE THREAD

**Issue by frumbert** [clickontyler/VirtualHostX-Issues#54]
I've ensured that nothing else is bound to port 80/443 and bound vhx7 to 80/443. I then added some sites - so "dev.vhx.host". I then destroyed and recreated the virtual machine, ensured it was running, and hit up the page "dev.vhx.host". This yields a "failed to open page" in safari; I checked /etc/hosts and there's no entries other than my other hand-coded ones.

**Comment by tylerhall** [comment]
All *.vhx.host domains are automatically routed to the correct IP address by my DNS server. There's no need to add them to your /etc/hosts file as previous versions of VHX had to.

**Comment by frumbert** [comment]
Is then something I need to do so that my browsers can actually see the sites? VHX is running, the ports are open, but I can't resolve any names.

**Comment by tylerhall** [comment]
Open up a terminal window and ping one of your domain names. Does it resolve to the correct local IP address?
