### ISSUE TITLE
Can't access *.vhx.host hostnames

### ISSUE THREAD

**Issue by mmrstudio** [clickontyler/VirtualHostX-Issues#57]
I can no longer access any *.vhx.host sites that I have setup through VHX7. Chrome gives me a "refused to connect" message, however If I ping them, it returns 127.0.0.1 which seems to be fine.

If I add an entry to my hosts file directly to the IP of the VHX Vagrant box for a given *.vhx.host address, eg.  "172.17.0.10  mysite.vhx.host" it works just fine.

Could there be something I'm missing with my system config?  Running Mac OS Sierra FYI.

**Comment by tylerhall** [comment]
Is this still happening for you on High Sierra?
