### ISSUE TITLE
PHP extensions cURL, mcrypt, and imagick not included on virtual box

### ISSUE THREAD

**Issue by wssrstrm** [clickontyler/VirtualHostX-Issues#60]
Needed to install these three extensions in order to get CraftCMS running locally, but they are pretty common extensions so I'm sure others would be able to make use of them if you permanently added them to the virtual box:

- cURL
- mcrypt
- imagick

Here is what I had to do to install each:

**cURL**

1. `sudo apt-get install libcurl3 php5-curl`
2. `sudo php5enmod curl`

**mcrypt**

1. `sudo apt-get install php5-mcrypt`
2. `sudo updatedb`
3. `locate mcrypt.ini` should show it located at /etc/php5/mods-available
4.  `locate mcrypt.so` 
5. Edit mcrypt.ini and change extension to match the path to mcrypt.so, example: `extension=/usr/lib/php5/20121212/mcrypt.so`
6. `sudo php5enmod mcrypt` (optional since its already enabled during phpmyadmin setup)

**imagick**

1. `sudo apt-get install php5-imagick`
2. `sudo php5enmod imagick`

**Comment by tylerhall** [comment]
These will now be included with VHX 7.3.
