### ISSUE TITLE
Update AllowOverride settings in apache2.conf from None to All

### ISSUE THREAD

**Issue by wssrstrm** [clickontyler/VirtualHostX-Issues#61]
Both ExpressionEngine and CraftCMS require this change to be made in order to be able to remove index.php from URL strings. Without this update, all URL strings will show index.php in the string, which is generally not the situation desired by most users.

So, currently, `/etc/apache2/apache2.conf`, is setup this way:

```
<Directory />
	Options FollowSymLinks
	AllowOverride None
	Require all denied
</Directory>

<Directory /usr/share>
	AllowOverride None
	Require all granted
</Directory>

<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>
```

I'm not sure if all these need to be chaged, but changing all of them to the below definitely got my CraftCMS intall working:

```
<Directory />
	Options FollowSymLinks
	AllowOverride All
	Require all denied
</Directory>

<Directory /usr/share>
	AllowOverride All
	Require all granted
</Directory>

<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>
```

**Comment by tylerhall** [comment]
You should be able to work around this by adding `AllowOverride All` to your VHX custom directives box. At least, that's what the box is there for. Email us if it doesn't work for you.
