### ISSUE TITLE
Self-signed SSL certificates

### ISSUE THREAD

**Issue by mattsims** [clickontyler/VirtualHostX-Issues#75]
I'm getting warnings in Chrome due to the SSL certificate being self-signed.  How do I specify alternative certificates to use?  I used to do this in v6 by modifying the .crt and .key paths in the generated VirtualHost directives for HTTPS, but this doesn’t seem to be an option in v7.

Any ideas?  Many thanks!

**Comment by tylerhall** [comment]
Hi, Matt. Sorry for the delay in getting back to you on this issue. It's not currently possible to specify an alternate SSL cert with VHX7. My only suggestion is to choose the "always trust" option for the self-signed cert in your browser.

**Comment by mattsims** [comment]
OK thanks Tyler 👍

**Comment by shadowhand** [comment]
Shouldn't it be possible to use LetsEncrypt to generate a SSL certificate for vhosts?
