### ISSUE TITLE
Need to change box's hostname from "default" to something unique

### ISSUE THREAD

**Issue by tylerhall** [clickontyler/VirtualHostX-Issues#77]

**Comment by BrettCrawley** [comment]
Not sure but it looks like you fixed this in the latest release?

If so thanks

**Comment by tylerhall** [comment]
I tried to fix it, but didn't think I succeeded. Is it now fixed for you?

**Comment by mountainash** [comment]
Not fixed for me (screenshot attached)

> The provider 'virtualbox' that was requested to back the machine 'default' is reporting that it isn't usable on this system.

Versions:
macOS 10.13.6
VirtualHostX 8.4.2
Vagrant 2.2.1

<img width="614" alt="screen shot 2018-11-27 at 6 28 46 pm" src="https://user-images.githubusercontent.com/27637/49065533-62a56480-f272-11e8-8f02-1ec2febbe9f6.png">

**Comment by mountainash** [comment]
It looks like downloading and installing the package from below fixed the problem.
https://www.virtualbox.org/wiki/Downloads
