### ISSUE TITLE
Cannot disable port 80/443 binding after enabling

### ISSUE THREAD

**Issue by shadowhand** [clickontyler/VirtualHostX-Issues#81]
It seems that once port 80/443 binding is selected, it is no longer possible to disable the port binding. This means that after restarting the vm, I have to re-trigger port binding or it fails.

Somewhat related to #44.

**Comment by tylerhall** [comment]
Sorry for the delay in reply - just now seeing this. If you hold down your keyboard's "Option" key, the "Bind to Ports..." menu command will change to "Unbind...".

Also, FYI just in case it wasn't obvious, the port binding doesn't persist across reboots of your Mac. You'll need to rebind each time you restart your Mac.

**Comment by tylerhall** [comment]
Port binding has been greatly improved in v8.6.0. The app auto-detects which ports are in use, and bindings now persist across reboots. Give it a try!
