### ISSUE TITLE
Fix Group Labels

### ISSUE THREAD

**Issue by tylerhall** [clickontyler/VirtualHostX-Issues#82]
http://shine.clickontyler.com/feedback-view.php?id=1283

Version: 47
System Version: 10.14.3
Importance: 
Criticality: 

Message: What did you expect to happen?
Folder ?group? label not to overlap folder icon (also folder icon is out of style with Apple design). Can add screenshot.

What steps will reproduce the problem?
Edit ?group? name by clicking on the folder name/label

**Comment by tylerhall** [comment]
This has been fixed and will be available in v8.7.0.

<img width="1375" alt="Screen Shot 2019-03-16 at 10 49 38 AM" src="https://user-images.githubusercontent.com/57670/54477805-368a0100-47d9-11e9-86c3-3e2f5b6ed82b.png">

**Comment by mountainash** [comment]
Nice - but in addition, maybe the "settings" panel on the right should also change when a folder is selected? (the 'Custom Directives' fields should be appear disabled as-well).

Or maybe folders just shouldn't be 'selectable'... a single click on a folder does nothing. Double click allows the name to be edited. A press and hold allows for re-ordering. And clicking the toggle arrow - opens and closes the folder. But a single click does nothing and the right panel stays showing the last selected website. Does that work?

**Comment by tylerhall** [comment]
Making the folders non-selectable causes some issues with displaying a context menu when you right-click on them. I may look into disabling selecting folders in a future release, but for the near future I’ll still allow it.

That said, the next app update will include fixes for stupid UI bugs where selecting a folder would show bogus values in the domain name text field and other places. Now, those fields appear empty and properly disabled.
