### ISSUE TITLE
Start page (website) shows PHP notice

### ISSUE THREAD

**Issue by shadowhand** [clickontyler/VirtualHostX-Issues#97]
<img width="421" alt="Image 2019-03-27 at 4 22 39 PM" src="https://user-images.githubusercontent.com/38203/55113294-b606b280-50ac-11e9-8bcf-df935f54f914.png">

Text of warning:

```
Your web server is running PHP 
Notice: Only variables should be passed by reference in /var/www/start.vhx.cloud/index.php on line 115
7.2.15.
```

**Comment by tylerhall** [comment]
Thanks! That will be fixed in v8.7.6.
