### ISSUE TITLE
PHPMyAdmin says it is not configured

### ISSUE THREAD

**Issue by shadowhand** [clickontyler/VirtualHostX-Issues#98]
When logging into PMA, the following warning is displayed at the bottom of the page:

<img width="902" alt="Image 2019-03-27 at 4 25 13 PM" src="https://user-images.githubusercontent.com/38203/55113380-0251f280-50ad-11e9-8fcb-88c08a31a114.png">

**Comment by tylerhall** [comment]
Looks like we need to set the initial secret in the config file.

**Comment by shadowhand** [comment]
@tylerhall yes, that is the main issue. The bundled version of PMA is also out of date.

The bit for "configuration storage" is a bonus but not necessary and probably not desirable in all situations. Also easy to configure from the web UI.

**Comment by tylerhall** [comment]
Great. I'll get PMA updated, too.

**Comment by tylerhall** [comment]
Fixed in v8.7.6.
