### ISSUE TITLE
"Generate new pin" dialogue opens on preferences open

### ISSUE THREAD

**Issue by mountainash** [clickontyler/VirtualHostX-Issues#99]
Every time the 'preferences' are opened, a "Generate new pin" dialogue is also spawned. It should only shown when the "Generate New Pin" button on the sharing pref' plane is clicked.

Version 8.7.0

**Comment by tylerhall** [comment]
@mountainash Can you update to v8.7.5 and see if it still happens?

**Comment by tylerhall** [comment]
I was able to reproduce this. Thanks for reporting. Fixed in v8.7.7.
